### ISSUE TITLE
updating the displayed array

### ISSUE THREAD

**Issue by phil-ho** [gilded-gliders/FEC#45]
https://github.com/gilded-gliders/FEC/blob/2703a9d1ba25453b50f6e7f2040154e0ab8dd88c/client/components/RelatedItems/RelatedProducts.jsx#L11

@yukiyamamoto710 is it necessary to use square brackets to create a new array, then spread the relatedItemsList into it, just to slice the resulting array again?

**Comment by yukiyamamoto710** [comment]
I was somehow thinking that the slice method would alter the original array but realized it does not. Will fix this across my all components. thanks!
